### ISSUE TITLE
Intellij issues in pom.xml

### ISSUE THREAD

**Issue by orozcoadrian** [codeTravels/Hangman#8]
any idea about this?

i get the following errors (highlighted red) in IntelliJ IDEA CE 2017.3:
```Plugin 'org.codehaus.mojo:jdepend-maven-plugin:2.0' not found
Plugin 'org.codehaus.mojo:jdepend-maven-plugin:2.0' not found
Plugin 'org.apache.maven.plugins:maven-jxr-plugin:2.5' not found
Plugin 'org.apache.maven.plugins:maven-jxr-plugin:2.5' not found
Plugin 'org.apache.maven.plugins:maven-pmd-plugin:3.8' not found
Plugin 'org.codehaus.mojo:findbugs-maven-plugin:3.0.5' not found
Plugin 'org.codehaus.mojo:findbugs-maven-plugin:3.0.5' not found
```

not sure if it's just an issue with my IDE.

i ran the jacoco:report plugin and i got the html report so that's working.

**Comment by codeTravels** [comment]
are you able to run mvn site from command line? Were you connected to the internet (to pull deps)? How did you try to run those plugins in IntelliJ?

**Comment by orozcoadrian** [comment]
i ran mvn site using the IDE and i got the site generated with all the reports generated correctly and after that all the red markings in the pom.xml went away :+1:
closing this issue.
